global:
  domain: 128.60.8.73.nip.io # Set this to the domain of your Openshift routes (or K8's services)
  openshift: true
  persistentStorage: true
  sourceRepositoryUrl: "https://github.com/coryk2049/sdp-helm-chart"
  sourceSecret: github

# something
jenkins:
  numAgents: 1 # Set this to the desired number of Jenkins Agents/Executors
  # Configure additional Jenkins variables as necessary
  subdomain: jenkins
  masterDockerContextDir: resources/jenkins-master
  agentDockerContextDir: resources/jenkins-agent
  resources:
    master:
      limits:
        cpu: "1000m"
        memory: "4000Mi"
      requests:
        cpu: "1000m"
        memory: "4000Mi"
    agent:
      limits:
        cpu: "1000m"
        memory: "1500Mi"
      requests:
        cpu: "1000m"
        memory: "1500Mi"
  dockerStorage: "20Gi"
  dockerDaemonArgs: "--insecure-registry docker-registry.default.svc:5000"

sonarqube:
  enabled: true
  # Configure additional Sonarqube variables as necessary
  resources:
    limits:
      cpu: "1500m"
      memory: "2000Mi"
    requests:
      cpu: "1500m"
      memory: "2000Mi"

selenium:
  enabled: true
  # Configure additional Selenium variables as necessary
  resources:
    limits:
      cpu: "250m"
      memory: "1000Mi"
    requests:
      cpu: "250m"
      memory: "1000Mi"

