kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jenkins
spec:
  selector:
      jenkins: master
  storageClassName: pv-jenkins
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/jenkins_home"