kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home
spec:
  storageClassName: gp2
#  storageClassName: pv-jenkins
#  capacity:
#    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
