kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data01
spec:
#  storageClassName: pv-data01
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi 
